# Generated by Django 3.2.6 on 2021-09-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='سبد خريد')),
            ],
            options={
                'verbose_name': 'سبد خريد',
                'verbose_name_plural': 'سبدهاي خريد',
            },
        ),
        migrations.CreateModel(
            name='CopounDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كد')),
                ('valid_from', models.DateTimeField(verbose_name='زمان شروع')),
                ('valid_to', models.DateTimeField(verbose_name='زمان انقضاء')),
                ('discount', models.IntegerField(verbose_name='مقدار تخفيف')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'كوپن تخفيف',
                'verbose_name_plural': 'كوپن هاي تخفيف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ايجاد')),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('R', 'ثبت'), ('T', 'سفارش')], default='T', max_length=1, verbose_name='وضعيف سفارش')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_orders', to='store.cart', verbose_name='سبد خرید')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='مشتري')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_addresses', to='accounts.address', verbose_name='آدرس سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='PercentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(verbose_name='درصد تخفيف ')),
                ('date_from', models.DateTimeField(verbose_name='تاريخ ايحاد')),
                ('date_valid', models.DateTimeField(verbose_name='تاريخ اعتبار')),
                ('active', models.BooleanField()),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ايجاد كننده ')),
            ],
            options={
                'verbose_name': 'تخفيف درصدي  ',
                'verbose_name_plural': 'تخفيفات درصدي  ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودي')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ايجاد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.book', verbose_name=' كتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='DiscountAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_dis', models.BigIntegerField(verbose_name='مقدار تخفيف')),
                ('time', models.DateTimeField(verbose_name='شروع تخفيف')),
                ('expire_date', models.DateTimeField(verbose_name='انقضاء تخفيف')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ايجاد كننده تخفيف')),
            ],
            options={
                'verbose_name': 'تخفيف نقدي ',
                'verbose_name_plural': 'تخفيفات نقدي ',
            },
        ),
    ]
