# Generated by Django 3.2.6 on 2021-09-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته بندي كتاب')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='ادرس دسته بندي')),
            ],
            options={
                'verbose_name': 'دسته بندي كتاب ',
                'verbose_name_plural': 'دسته بندي كتاب ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان كتاب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس كتاب ')),
                ('author', models.CharField(blank=True, max_length=140, null=True, verbose_name='نويسنده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ايجاد')),
                ('inventory', models.IntegerField(verbose_name='موجودي ')),
                ('price', models.BigIntegerField(verbose_name='قيمت')),
                ('image', models.ImageField(blank=True, upload_to='./image', verbose_name='عکس')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندي')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'كتاب ها',
            },
        ),
    ]
