# Generated by Django 3.2.6 on 2021-09-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
